---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "integration-manager-worker.fullname" . }}
  {{- if .Values.namespaced }}
  namespace: {{ template "integration-manager-worker.namespace" . }}
  {{- end }}
  labels:
    app: integration-manager-worker
    chart: {{ template "integration-manager-worker.chart" . }}
    release: {{ .Release.Name | quote }}
    destinationId: {{ quote .Values.destinationId }}
data:
  worker.properties: |
    #worker specific properties
    server.port=5000

    job.results.queue-name={{ .Values.resultsQueue }}

    #AMQP Properties
    queue.host=${rabbitmq-host}
    queue.port={{ .Values.amqp.port }}
    queue.username=${rabbitmq-username}
    queue.password=${rabbitmq-password}
    queue.ssl.enabled={{ .Values.amqp.ssl }}

    sharedDataPath=/opt/Actian
    installPath=/opt/Actian

    # Worker configuration
    worker.concurrency={{ .Values.concurrency }}
    worker.destinationId={{ .Values.destinationId }}
    worker.engineJavaHome=${sharedDataPath}/engine/jre
    worker.libraryPath=/opt/Actian/lib
    worker.workerLocalDir=${sharedDataPath}/local/work
    worker.api.port=5000
    
    # Dataflow Configuration
    dataflow.enabled=true
    dataflow.licensePath=${sharedDataPath}/volume/cosmos.slc
    dataflow.localEngineInstallPath=${sharedDataPath}/dataflow/bin
    dataflow.localEngineRemoteJvmArgs=-Xms64m -Xmx1g
    dataflow.charset=utf-8
    dataflow.strictMode=disabled
    
    # Link Flow Command Server
    link.enabled=true
    link.localEngineInstallPath={{ .Values.linkEnginePath }}

    # Engine Configuration (for this Worker)
    engine.iniFilePath=${sharedDataPath}/conf/cosmos.ini
    engine.licensePath=${sharedDataPath}/volume/cosmos.slc
    engine.localEngineInstallPath=${sharedDataPath}/engine/runtime/di9
    engine.localEngineListenerPort=4999
    engine.localEngineRemoteJvmArgs=-Xms64m -Xmx1g
    engine.allowAllExecutables=false
    #engine.executableWhiteList=

    {{- if .Values.extraConfig }}
    {{ .Values.extraConfig | indent 4 | trim }}
    {{- end }}
---
