---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "integration-manager-worker.fullname" . }}
  {{- if .Values.namespaced }}
  namespace: {{ template "integration-manager-worker.namespace" . }}
  {{- end }}
  labels:
    app: integration-manager-worker
    chart: {{ template "integration-manager-worker.chart" . }}
    release: {{ .Release.Name | quote }}
    destinationId: {{ quote .Values.destinationId }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: integration-manager-worker
      release: {{ .Release.Name | quote }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- if .Values.podAnnotations }}
        {{ .Values.podAnnotations | toYaml | indent 8 | trim }}
        {{- end }}
      labels:
        app: integration-manager-worker
        chart: {{ template "integration-manager-worker.chart" . }}
        release: {{ .Release.Name | quote }}
        destinationId: {{ quote .Values.destinationId }}
        {{- if .Values.extraLabels }}
        {{ .Values.extraLabels | toYaml | indent 8 | trim }}
        {{- end }}
    spec:
      {{- if .Values.affinity }}
      affinity:
        {{ .Values.affinity | toYaml | indent 8 | trim }}
      {{- end }}
      serviceAccountName: {{ template "integration-manager-worker.fullname" . }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{ .Values.nodeSelector | toYaml | indent 8 | trim }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      enableServiceLinks: false
      initContainers:
      - name: dataconnect-engine
        image: {{ .Values.dcEngineImage }}
        imagePullPolicy: {{ .Values.dcEngineImagePullPolicy }}
        command: ['sh', 'script.sh']
        securityContext:
          {{- toYaml .Values.dcEngineSecurityContext | nindent 10 }}
        volumeMounts:
        - name: dataconnect-engine-vol
          mountPath: /opt/Actian/engine
      - name: link-engine
        image: {{ .Values.linkEngineImage }}
        imagePullPolicy: {{ .Values.linkEngineImagePullPolicy }}
        command: [ "/bin/sh","-c","/opt/install/install_flowcmdserver_standalone_installation_dist.sh && chown -R 1000:1000 /opt/link/" ]
        securityContext:
          {{- toYaml .Values.linkEngineSecurityContext | nindent 10 }}
        volumeMounts:
        - name: link-engine-vol
          mountPath: /opt/link/flowcmdserver_standalone_installation
      - name: dataflow-engine
        image: {{ .Values.dfEngineImage }}
        imagePullPolicy: {{ .Values.dfEngineImagePullPolicy }}
        command: ["/bin/sh","-c"]
        args: ["chmod +x script.sh && ./script.sh; chmod -R 755 /opt/Actian/dataflow/conf"]
        securityContext:
          {{- toYaml .Values.dfEngineSecurityContext | nindent 10 }}
        volumeMounts:
        - name: dataflow-engine-vol
          mountPath: /opt/Actian/dataflow
        {{- if .Values.logstream.enabled }}
      - name: init-enginelog
        image: {{ .Values.busybox.image.repository}}:{{ .Values.busybox.image.tag}}
        imagePullPolicy: {{ .Values.busybox.image.pullPolicy }}
        command: ['sh', '-c', 'chown -R 1000:3000 /opt/Actian/local/work/job']
        securityContext:
          {{- toYaml .Values.engineLogSecurityContext | nindent 10 }}
        volumeMounts:
        - name: enginelog
          mountPath: /opt/Actian/local/work/job
        {{- end }}
      - name: init-dcodbc
        image: {{ .Values.dcOdbcImage }}
        imagePullPolicy: {{ .Values.dcOdbcImagePullPolicy }}
        command: ['sh', 'script.sh']
        securityContext:
          {{- toYaml .Values.dcOdbcSecurityContext | nindent 10 }}
        volumeMounts:
        - name: datacloud-odbc-vol
          mountPath: /opt/Actian/Actian_Client
        - name: datacloud-odbcinst-vol
          mountPath: /opt/Actian/odbcconfig        
      containers:
      - name: worker
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: WORKER_CONFIGMAP_NAME
          value: {{ template "integration-manager-worker.fullname" . }}
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/secrets/gcp/gcp-secret
        ports:
        - containerPort: 5000
        lifecycle:
          preStop:
            exec:
              # Stop worker from picking up more jobs and send SIGKILL once /worker/poke is no longer available (All jobs have completed)
              # Added sleep 30 at start to allow enough time for container to start up
              command: ["/bin/sh", "-c", "sleep 30 && if [ $(curl -X 'DELETE' -I --silent -o /dev/null -w %{http_code} http://localhost:5000/worker/shutdown) == 202 ] ; then until [[ $(curl -I --silent -o /dev/null -w %{http_code} http://localhost:5000/worker/poke) != 200  ]] ;do printf '.'; sleep 5; done; else kill -11 1; fi;"]
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        volumeMounts:
        - name: worker-shared-volume
          readOnly: true
          mountPath: /etc/config
        - name: secret-volume
          readOnly: true
          mountPath: /etc/secrets
        {{- if .Values.existingRabbitSecret }}
        - name: amqp-secret-volume
          readOnly: true
          mountPath: /etc/secrets/amqp
        {{- end }}
        - name: license-vol
          readOnly: true
          mountPath: /opt/Actian/volume
        - name: gcp-secrets
          readOnly: true
          mountPath: /etc/secrets/gcp
        - name: dataconnect-engine-vol
          mountPath: /opt/Actian/engine
        - name: tmp
          mountPath: /tmp
          readOnly: false
        - name: job-workspace
          mountPath: /opt/Actian/local
          readOnly: false
        - name: app-config
          mountPath: /opt/Actian/conf
          readOnly: false
        - name: enginelog
          mountPath: /opt/Actian/local/work/job
          readOnly: false
        - name: dataflow-engine-vol
          mountPath: /opt/Actian/dataflow
          readOnly: false
        - name: link-engine-vol
          mountPath: /opt/link/flowcmdserver_standalone_installation
          readOnly: false
        - name: datacloud-odbc-vol
          mountPath: /opt/Actian/Actian_Client
          readOnly: false
        - name: datacloud-odbcinst-vol
          mountPath: /opt/Actian/odbcconfig
          readOnly: false         
               
        {{- if .Values.extraVolumeMounts }}
        {{ .Values.extraVolumeMounts | toYaml | indent 8 | trim }}
        {{- end }}
        livenessProbe:
          {{ .Values.livenessProbe | toYaml | indent 10 | trim }}
        {{- if .Values.resources }}
        resources:
          {{ .Values.resources | toYaml | indent 10 | trim }}
        {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      volumes:
      - name: gcp-secrets
        secret:
          {{- if .Values.existingGcpSecret }}
          secretName: {{ .Values.existingGcpSecret }}
          {{- else }}
          secretName: {{ template "integration-manager-worker.fullname" . }}-gcp
          {{- end }}
      - name: worker-shared-volume
        configMap:
          name: {{ template "integration-manager-worker.fullname" . }}
      - name: secret-volume
        secret:
          {{- if .Values.existingSecret }}
          secretName: {{ .Values.existingSecret }}
          {{- else }}
          secretName: {{ template "integration-manager-worker.fullname" . }}
          {{- end }}
      {{- if .Values.existingRabbitSecret }}
      - name: amqp-secret-volume
        secret:
          secretName: {{ .Values.existingRabbitSecret }}
          items:
          - key: rabbitmq-host
            path: rabbitmq-host
          - key: rabbitmq-username
            path: rabbitmq-username
          - key: rabbitmq-password
            path: rabbitmq-password
      {{- end }}
      - name: license-vol
        configMap:
          name: {{ template "integration-manager-worker.fullname" . }}-license
      - name: dataconnect-engine-vol
        emptyDir: {}
      - name: dataflow-engine-vol
        emptyDir: {}
      - name: link-engine-vol
        emptyDir: {}
      - name: datacloud-odbc-vol
        emptyDir: {}
      - name: datacloud-odbcinst-vol
        emptyDir: {} 
      - name: tmp
        emptyDir: {}
      - name: job-workspace
        emptyDir: {}
      - name: app-config
        emptyDir: {}
      - name: enginelog 
        {{- if .Values.logstream.enabled }} 
        hostPath:
          path: {{ .Values.logstream.hostPath }}
          type: '' 
        {{- else }}
        emptyDir: {}
        {{- end }}

      {{- if .Values.extraVolumes }}
      {{ .Values.extraVolumes | toYaml | indent 6 | trim }}
      {{- end }}
