{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "integration-manager-worker.fullname" . }}
  {{- if .Values.namespaced }}
  namespace: {{ template "integration-manager-worker.namespace" . }}
  {{- end }}
  labels:
    app: integration-manager-worker
    chart: {{ template "integration-manager-worker.chart" . }}
    release: {{ .Release.Name | quote }}
    destinationId: {{ quote .Values.destinationId }}
type: Opaque
data:
  {{- if not .Values.existingRabbitSecret }}
  rabbitmq-host: {{ .Values.amqp.host | b64enc }}
  rabbitmq-username: {{ .Values.amqp.username | b64enc }}
  rabbitmq-password: {{ .Values.amqp.password | b64enc }}
  {{- end }}
{{- end }}
---
{{- if not .Values.existingGcpSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "integration-manager-worker.fullname" . }}-gcp
  {{- if .Values.namespaced }}
  namespace: {{ template "integration-manager-worker.namespace" . }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.gcpSecret }}
  gcp-secret: {{ .Values.gcpSecret | b64enc | indent 4 | trim  }}
  {{- end }}
{{- end }}
---
{{- if not .Values.existingLicenseSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "integration-manager-worker.fullname" . }}-license
  {{- if .Values.namespaced }}
  namespace: {{ template "integration-manager-worker.namespace" . }}
  {{- end }}
  labels:
    app: integration-manager-worker
    chart: {{ template "integration-manager-worker.chart" . }}
    release: {{ .Release.Name | quote }}
    destinationId: {{ quote .Values.destinationId }}
type: Opaque
data:
  {{- if .Values.dc12license }}
  cosmos.slc: |
  {{ .Values.dc12license | toString | b64enc | trim | indent 4 }}
  {{- end }}
{{- end }}
