{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "integration-manager-worker.fullname" . }}
  {{- if .Values.namespaced }}
  namespace: {{ template "integration-manager-worker.namespace" . }}
  {{- end }}
  labels:
    app: integration-manager-worker
    chart: {{ template "integration-manager-worker.chart" . }}
    release: {{ .Release.Name | quote }}
    destinationId: {{ quote .Values.destinationId }}
type: Opaque
data:
  {{- if not .Values.existingRabbitSecret }}
  rabbitmq-host: {{ .Values.amqp.host | b64enc }}
  rabbitmq-username: {{ .Values.amqp.username | b64enc }}
  rabbitmq-password: {{ .Values.amqp.password | b64enc }}
  {{- end }}
{{- end }}

{{- if .Values.namespaced }}
---
{{- if .Values.externalSecrets.enabled }}
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: dockerhub-actian-registrykey
  {{- if .Values.namespaced }}
  namespace: {{ template "integration-manager-worker.namespace" . }}
  {{- end }}
spec:
  template:
    type: kubernetes.io/dockerconfigjson
  backendType: {{ .Values.externalSecrets.backendType }}
  {{- if .Values.externalSecrets.keyVaultName }}
  keyVaultName: {{ .Values.externalSecrets.keyVaultName }}
  {{- end}}
  data:
    - key: {{ .Values.externalSecrets.keyName }}
      name: .dockerconfigjson
      property: {{ .Values.externalSecrets.keyProperty}}
{{- end}}

{{- if not .Values.externalSecrets.enabled }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: dockerhub-actian-registrykey
  {{- if .Values.namespaced }}
  namespace: {{ template "integration-manager-worker.namespace" . }}
  {{- end }}
data:
  .dockerconfigjson: {{ .Values.dockerConfiguration }}
{{- end}}

{{- end}}

---
{{- if not .Values.existingGcpSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "integration-manager-worker.fullname" . }}-gcp
  {{- if .Values.namespaced }}
  namespace: {{ template "integration-manager-worker.namespace" . }}
  {{- end }}
type: Opaque
data: 
  {{- if .Values.gcpSecret }}
  gcp-secret: {{ .Values.gcpSecret | b64enc | indent 4 | trim  }}
  {{- end }}
{{- end }}
